### ISSUE TITLE
Configuring Demo Data for WDS in Hot mode

### ISSUE THREAD

**Issue by qosmy-michael** [bencripps/react-redux-grid#1]
I'm testing the grid standalone - using WDS.  

webpack-dev-server --hot --inline --pretty --config webpack/webpack.config.hot.js

Grid renders on :8080, but no data in it.

How do I configure the demo provider to load the sample data?

you have an endpoint in DemoData.js

GET http://localhost:3000/getfakeData 404 (Not Found)

I changed it to the WDS default 8080

GET http://localhost:8080/getfakeData 404 (Not Found)

still didn't work  - Thanks! Michael

**Comment by bencripps** [comment]
Thanks for sending the issue!

Looks like you're building the component successfully, but that data isn't loading. I've pushed a new commit 07efce0 which provides better documentation for instantiating a grid with data, as well as updated the `demo/ ` version of the grid to use a remote data source rather than a fake localhost address.

The reason your `404ing` on the `GET` of grid data is because there is no server provided with the grid component. With the latest commit, you should be able to clone the newest version and the grid will just work (because its requesting data from a real live web server), but I've also updated the documentation so it's more clear how a grid should get data.

Let me know if this helps.

**Comment by qosmy-michael** [comment]
Works great - thanks for the clarification!
