### ISSUE TITLE
General ideas and enhancement requests.

### ISSUE THREAD

**Issue by darlenya** [bencripps/react-redux-grid#116]
Hi benjamin,

I just have written what functionality I need for our use case.
I am willing to implement the features but I would need your help
in better understanding the code and the ideas behind it.
If you like we can talk about it.

Needs for us:
- row renderer
	Solved: It is important that we can render rows in different colors
- column renderer
	I need to render columns in different color.
	I think there is also a little work to to. At the moment the column renderer renders not 
	the <td> element. This leads to only render the inner part of the cell. 
- save column width
	The user may change the width of the columns as he needs it. This must be saved
	so the next time the user opens the table it has the same column width
- The model data should be accessed by functions instead of providing a model made for the view.
	Why is this important? My model has a lot of validation, checking and calculation logic.
	If I provide a model to the table I have to reimplement the whole logic for this specific model
	or for each change I have to transfer the table model to my model. Do checking and validation  then convert the model back to the table model.
- Horizontal scrolling
	As I told in my request I have tables with hundred of columns
- Fixed columns
	As must be possible to fix the columns on one side. Like it is in Excel.
- Fixed rows
	Not only the header row should be fixed. It should also possible to fix more rows.
- collaps rows
	Exists

Ideas:
- column renderer
	The column renderer should also be provided via the plugin. It makes no sense to have different column 
	renderer. I think its better to have one provided. This renderer could use than different ones depending
	on the column.
	If the user adds a new column, which renderer should be taken if there are different ones

**Comment by bencripps** [comment]
Thanks for the feedback.

1. Row Renderer
 PR in progress, nearly ready to merge.

2. Column Renderer
I think it's possible to change the column renderer to work just like the row renderer, in that it renders the entire column, however, I think it should be provided on the `columns` defintion rather than the plugin since it's specific to the column, and not all columns (like the row renderer).

3. Save Column Width
This feature already exists. Just pass `stateful: true` as a top level grid parameter.

4. Model Functions
Not sure exactly what you mean, could you provide an example?

5. Horizontal Scrolling
Yes, this would be a nice feature to add, but it will be tough. See #114 

6. Fixed Columns
Again, not entirely sure what you mean. Could you provide an example?

7. Fixed Rows
Seems possible, and would be willing to consider adding feature.

**Comment by darlenya** [comment]
Some explanations.

2. Yes and no. Which column renderer will be added if I insert a new column via a menu action. This is not so important. Is more an idea.

4. For example I have a model where the data is stored as columns. Then to provide the data to the table I have to create a new data structure.
Updates  on the table model then have to be transfered to the original model. Then I can do the checks and calculations. Then again need to recreate the model for the table. So there are a lot mof model migrations. This will happen for each change.
	
An alternative could be that like it is for the data source I provide a function getColumns() getRowCount() and getRowById(id) and then I do not need to convert my original model. I think in this case I also have to provide custom reducer. 

6. Like it is in excel when you fix it. So I can set the first 2 coluns to fixed. Then horizontal scrolling only affects column 3 to n.

**Comment by bencripps** [comment]
Since these are just general comments, closing this issue. Feel freel to issue PR's around these topics.
