### ISSUE TITLE
multiple grid interaction question

### ISSUE THREAD

**Issue by kkwak** [bencripps/react-redux-grid#26]
not sure where to post questions!

Wanted to know how multiple table interactions should be handled... Right now, I've got multiple table each loading it's own data (each one being a component). 

I have some grids which require other table data - it'd be easier if the data were loaded on to a user controllable key 
Accessing the data is quite difficult: state.getState().dataSource["stateKey"].data (right?)
Also there are loads of duplicates - my app is running at 400MB+ at the moment and I'm not doing much! 😆 

**Requirement 1:**
Grid - Car Types
Grid - Car Makes/Model

Makes/Model requires Car Types data - so if it's not loaded I want to load it up first, then load the makes/model dataSource.. 

So the concept of dependent dataSources? Or hierarchical sources? Not if it's that's important to you at all.. If I have to do it, then I'd have to manage all the data myself - I suppose. Just wanted to double check.

(As a side comment - would be great to have an api to grab the data quickly.. data[stateKey] or something that is stable..

**Requirement 2:**
Removing the data cache - last mentioned above, I need to mark certain grids to not cache when data is not shown - some tables are big and should fetch them again if needed. I'd be nice to have a marker I could use to denote this

Let me know if this is important to you - and if I can assist... Otherwise, if you would be able to provide some guidance/suggestion that'd swell.

**Comment by bencripps** [comment]
Both of these use cases sound very specific to your implementation so it doesn't sound like these would be good fits to be incorporated into the component.

Duplicates? 400mb? What do you mean? What is 400mb? Could you post a screen shot of what you're talking 

You are correct, this is the right way to get data:

````js
state.getState().dataSource["stateKey"].data
````

I don't think it makes sense to export something like this from the package -- it would be awesome if the `Grid` component itself could have static methods like `getData`, but it's just a JSX component which accepts `props`, that doesn't work. And because of that, we would also have to export `getSelectionModel`, `getProxy`, etc, which would balloon the total export.

I would recommend making some helper functions you can use in your own application, that match your needs.

Thanks! Let me know if you have any other questions!

**Comment by bencripps** [comment]
Closing this issue as it's requesting enhancements that are not being considered.
