### ISSUE TITLE
data property is not connected

### ISSUE THREAD

**Issue by innopal** [bencripps/react-redux-grid#30]
Hi Ben,

It seems like changes to data property doesn't force re-render.
I looked at the code and it seems like in util/mapStateToProps, the code is ignoring data and only listening to dataSource:
gridData: stateGetter(state, props, 'dataSource', props.stateKey),

Will you please look into this?

One more question: What's the difference between Grid and ConnectedGrid?

Cheers.

**Comment by bencripps** [comment]
### Issue #30

Investigating now!

I have a question though; How are you updating data? Are you using an action, or are you simply changing the passed in props (either should work, I'm just curious).

To change via an action you would call:

````js
store.dispatch(Actions.GridActions.setData({ stateKey: 'unique', data: [] });
````

I'm going to investigate both situations, but it would be helpful to know more about your issue.

### As for your question about connected v unconnected grid:

The package exports include the `actions`, the `reducers`, a `store`, and the `grid`. The unconnected grid isn't exported, as it wouldn't do anyone any good -- you will need to use the `redux` connected grid so that state can be maintained and updated internally. 

Let me know if that helps!

**Comment by innopal** [comment]
Thanks Ben,

I'm not using Actions just changing the data in props like:
<Grid {...config} data={this.props.myList} />

I can give using the GridActions a try and let you know.

The reason I asked about CoonectedGrid was that I saw this line of code:
const ConnectedGrid = connect(mapStateToProps)(Grid);
export { Grid, ConnectedGrid };

..and I thought maybe I need to import ConnectedGrid instead of Grid.

Cheers.

**Comment by bencripps** [comment]
The main exports are as follows:

````js
const modules = {
    Actions,
    Grid: ConnectedGrid,
    GridRootReducer: combineReducers(Reducers),
    Reducers,
    Store
};
`````

So when you're using `Grid`, it is actually the connected version Hope that helps!

**Comment by bencripps** [comment]
@innopal any news on this one? I haven't been able to reproduce this issue myself.

**Comment by innopal** [comment]
Hi Ben,

Dispatching the action worked as you suggested, but it is not working without dispatching.

I was hoping something like this would work(but it doesn't) out of the box:

```
render() {
  return <Grid {...config} data={this.props.myList} />
}
...
const mapStateToProps = (state) => ({
  myList: state.myList
});

export default connect(mapStateToProps)(MyComponent);
```

**Comment by bencripps** [comment]
Hmm, seems like it should work that way though. I will see if I can repro, and commit the fix.

**Comment by bencripps** [comment]
After trying a few solutions, I've finally landed on one. I'm going to publish as a feature branch for now. Would you mind installing it, running `npm dist` and seeing if this fixes your issue?

I've written a test around it, which shows that it works, but I want to make sure it fixes your specific use case.

**Comment by innopal** [comment]
Sure! What's the branch?

**Comment by bencripps** [comment]
https://github.com/bencripps/react-redux-grid/tree/feature/connect-data

feature/connect-data

**Comment by bencripps** [comment]
I ran a simple demo that confirms this works, so I've merged it into master. Will do a release as well.

**Comment by innopal** [comment]
Perfect! Thanks @bencripps.
