### ISSUE TITLE
Question: column customization with multiple data fields

### ISSUE THREAD

**Issue by kayazinc** [bencripps/react-redux-grid#32]
The data schema as followed:
``{ symbol: 'AAPL', name: 'Apple', close: 123.45 }``

Assuming there are 2 columns in the table: Stock and Price.  The Stock column will render two fields: symbol and name.  ``<div>{symbol}</div><div>{name}</div>``

Based on your example, my Stock column will be something like below:
<pre><code>export const stockColumn = [
    {
        name: 'Stock',
        dataIndex: 'symbol + name',  // <--- what should be the input for multiple fields?
        renderer: ({ column, value, row }) => {
            // can the value be a object containing symbol and name?
            ...
        }
    }
];</code></pre>

Please advise me.  Thanks in advance!

**Comment by bencripps** [comment]
For something like this, where you'd like to combine two data entries into a single column you should use a custom `renderer`. The implementation would like something like this: 

````js
const columns = [
    {
        name: 'Combined Column',
        dataIndex: 'it-wont-matter',
        renderer: ({ column, value, row }) => {
            return (
                <div>
                    <span> { row.stock } </span>
                    <span> { row.symbol } </span>
                </div>
            );
        }
    }, // ... rest of columns
];
````

Since the `renderer` determines what the final output will be, it's not important what the `dataIndex` for the column is. Let me know if you need more information.

**Comment by kayazinc** [comment]
Thanks again @bencripps, let me go try it out.
