### ISSUE TITLE
Request: make project ready for distribution

### ISSUE THREAD

**Issue by kayazinc** [bencripps/react-redux-grid#36]
First of all, I am new to javascript.  So pardon me if I am asking for too much or asking too many questions.

@bencripps, may I request to make this project "distributable" ready?  What I meant by "distributable" is to have a "dist" folder with the scripts (compiled) and ready for use.  The reason for this request is because I am struggling to compile / setup react-redux-grid into my main project.

Thanks for the wonderful component regardless.

**Comment by bencripps** [comment]
I'm working on this one, but thanks for posting this issue!

I 100% agree, the project needs a `dist` so it doesn't have a hard dependency on webpack. I've got a feature branch open, `feature/dist`, which is about 90% there. I've run into a snag with the `babel-stylus-plugin-compiler` which is breaking the stylus package on build -- I've posted an issue on the repository so hopefully that gets resolved soon. 

I'm also looking at other options. I will post again ASAP one I get this feature branch merged into master.

**Comment by kayazinc** [comment]
Thanks @bencripps, great to hear that!

**Comment by bencripps** [comment]
Grid v2.0.0 has been published, and includes a dist folder.

Since we are now shipping with built code, the fonts have been removed. Grid icons come from font-awesome, so it will now be a developer responsibility to ensure that font-awesome is available at execution time. Let me know if you have any questions; you can checkout the demo for a very simple way of incorporating font-awesome.

**Comment by kayazinc** [comment]
Got it, thanks again @bencripps!
