### ISSUE TITLE
Question: Why does grid tree require both nested children and a parentId field?

### ISSUE THREAD

**Issue by jktravis** [bencripps/react-redux-grid#58]
Hi, 

Thanks for making this open source. It seems to be the most feature-rich one that I have seen. But I am curious as to why the tree view has the above requirement. How does it perform if there are thousands of records with a varying degree of nesting?

**Comment by bencripps** [comment]
Great question. And in fact, the answer to your first question leads into your second.

### Why does Tree View require a `children` and `parentId` parameter

Although the tree view depicts a hierarchical structure, the resulting DOM is a flat list of records. This architecture provides a seamless transition between a flat grid, and a tree grid. Because the tree is based on a flat list, it's necessary to have more metadata about each row (specifically `parentId`). This leads me to your second question.

### How does the tree view perform with thousands of records of varying nestedness 

Because our goal is to have an extremely performant grid, we decided to require both `parentId` and `children` rather than putting the onus on grid to map out the relationship. We want to be able to render and manipulate data on the fly, without requiring a mapping function to translate data. This is especially important when it comes to drag and drop, but it's also important when you begin to scale data sizes. 

Currently, the grid scales to around 2000 records with minimal lag. However, with larger data sets, there simply results in too much DOM which slows down updates, and creates visible jank. We're currently working on a feature that will make much larger data sets possible (we're aiming for around 50,000 with ease).

Once that feature is finished, it will be published as a new major release.

### Tips for using large data sets with Tree View

It's recommended that tree data be loaded progressively. If you're loading data using a remote source, you can opt to only load a subset of your tree, requesting further data when nodes are expanded. 

### Work arounds 

Since I don't think we want to add this feature, I would recommend using a utility to map your data before it's passes to Grid.

**Comment by jktravis** [comment]
Thanks for the quick response, Ben.
