### ISSUE TITLE
Event handler and arguments

### ISSUE THREAD

**Issue by whatisboom** [bencripps/react-redux-grid#75]
I noticed a bug/issue when digging into the HANDLE_CELL_CLICK code in [Cell.jsx](https://github.com/bencripps/react-redux-grid/blob/master/src/components/layout/table-row/row/Cell.jsx#L236) this line is being transpiled into `return events.HANDLE_CELL_CLICK.apply(undefined, _arguments);`  and `_arguments` is definitely not the scope we need here. I'm unsure if this is a bug with Babel, or with the babel/webpack config.

**Comment by bencripps** [comment]
Honestly, this is a little sloppy on my end. Rather than applying the `arguments` to the `HANDLE_CELL_CLICK` and the `HANDLE_CELL_DOUBLE_CLICK` events, I'd rather pass them an explicit set of args.

This is also something I'd like to standardize across all grid events in the future. Since making these changes is breaking, I'd prefer to make all the changes at one time, and release them as a new major.

Do you have a preference for how you'd like to see event arguments composed?

I think we would have to load a lot of metadata for each, call since many events are context specific, but they could be undefined if they weren't available at scope.

````js
HANDLE_SOME_EVENT = ({ 
    editor,
    events,
    isSelected,
    row,
    rowId,
    rowIndex
}) => {};
````

Ideally, every event function would have this shape. Is there anything else you'd like to see added? 

Again, since this is a breaking change, I propose getting this work done in a feature branch and merging as a new major release. Are you currently broken, or can you work with what is currently there?

**Comment by whatisboom** [comment]
Definitely not breaking/blocker for me at the moment, I just stumbled across it while looking over function signatures in the documentation and noticed some inconsistencies.

**Comment by bencripps** [comment]
Is there anything missing from that function call that you'd like to see?

**Comment by whatisboom** [comment]
LGTM 👍

**Comment by bencripps** [comment]
````js
export const handleEvent = (name, events, context = {}, browserEvent) => {
    if (!events || typeof events[name] !== 'function') {
        return;
    }

    events[name]({
        editor: context.editor,
        events,
        isSelected: context.isSelected,
        row: context.row,
        rowId: context.rowId,
        rowIndex: context.rowIndex
    }, browserEvent);

};
````

**Comment by bencripps** [comment]
All grid event handlers now accept the same shaped arguments. Releasing as new major.
