### ISSUE TITLE
Grid Menu not Showing

### ISSUE THREAD

**Issue by leonfs** [bencripps/react-redux-grid#8]
I tried to use the Grid Menu (by including the GRID_ACTIONS object into the plugins object).

```
GRID_ACTIONS: {
        iconCls: 'action-icon',
        menu: [
            {
                text: 'Delete',
                EVENT_HANDLER: () => {
                    alert('hi');
                }
            }
        ]
    }
```

I can see the icon, but when I click on it nothing happens. No menu is displayed (as the one displayed on the demo)

Something I noticed is that I have an UNMET PEER dependency when I installed react-redux-grid. Maybe that's connected to the problem?

`
--> UNMET PEER DEPENDENCY history@^1.17.0
`

**Comment by bencripps** [comment]
Could you provide the full object your passing to the grid?

**Comment by leonfs** [comment]
Hi Ben,

Thanks for the quick reply. 

The object is: 

```
const colums = [... My column definitions]
const pageSize = 20;
const height = '100%';
const events = {
            HANDLE_ROW_CLICK: (cell, reactEvent, id, browserEvent) => {
                 console.log('row clicked');
            }
        }
const plugins = {
GRID_ACTIONS: {
        iconCls: 'action-icon',
        menu: [
            {
                text: 'Delete',
                EVENT_HANDLER: () => {
                    alert('hi');
                }
            }
        ]
    }
}
const gridData = {
            columns,
            dataSource: submissionsUrl,
            pageSize,
            events,
            plugins,
            height
        };
```

**Comment by bencripps** [comment]
The config looks good but there's a couple issues here that could be causing some problems.

I don't see a `store` being passed to grid -- the `store` is a required parameter, as all component state is managed through the store.

## If you are passing a store:

1. Is it a custom store, or is it the store exposed from the main `react-redux-grid` export?
1a. If its a custom store, you will need to include the grid `reducers` which listen for `actions` like `SHOW_MENU`.
1b. If you want to use the built in store, make sure you pass it to the `grid` instantiation. You won't need to pass `reducers` with this store, since they will be combined at startup.

## If you are not passing a store:

1. The `grid` exposes a store from the main export. 

```
import { Grid, Store } from 'react-redux-grid';

const grid = <Grid { ...{ store: Store }  } />;
```

## Conclusion

With your config, the grid shouldn't load at all. It should throw an error immediately. Let me know if you are/are not passing a store -- but

1. if you are not passing a store and the grid loads, that's an issue.
2. if you are passing the built in store, and the menu doesn't show, that's an issue.

Are there any errors in the console?

**Comment by leonfs** [comment]
Hi Ben,

Sorry. My bad. I was adding the Store as a separate prop and data was being shown on the Grid.

What I forgot to add is the appropriate reducer for the menu (GridReducers.Menu). 

Thanks for being so quick on responding and for the amazing project you built.

Leo.-

**Comment by leonfs** [comment]
Actually, I still have an issue. Now I see the menu (with 2 elements on the menu array).

```
GRID_ACTIONS: {
                iconCls: 'action-icon',
                menu: [
                    {
                        text: 'On Hold',
                        EVENT_HANDLER: (ev) => {
                            const state = 'OnHold';
                            const projectId = ev.metaData.rowData.Id;
                            store.dispatch(updateProjectState(projectId, state));
                        }
                    },
                    {
                        text: 'Check',
                        EVENT_HANDLER: (ev) => {
                            const state = 'Checked';
                            const projectId = ev.metaData.rowData.Id;
                            store.dispatch(updateProjectState(projectId, state));
                        }
                    }
                ]
            }
```

But only 1 (OnHold) shows up. 

Do you know what can it be? I'm using the following reducers.

```
dataSource: gridReducers.DataSource,
  grid: gridReducers.Grid,
  filter: gridReducers.Filter,
  menu: gridReducers.Menu,
```

Cheeers

**Comment by leonfs** [comment]
So.. I basically debugged the plugin. 

And I found the problem to be in the following function:
```
export const getUniqueItems = (items) => {
    const keys = items.map((obj) => { return obj.key; });
    const unique = items.filter((ob, i) => { return keys.indexOf(ob.key) === i; });
    return unique;
};
```

My menu array had objects without 'key' property. I basically copied the example from the demo folder as actually there is no documentation on the Readme about the menu plugin. But the demo folder is missing the key property. 

Cheers.

**Comment by bencripps** [comment]
Yup! Spot on. Since the `menuItems` will be rendered as jsx elements, a unique key is required. I will add some documentation about the menu plugin, including a note that a `key` is required for each item. I will also update the `demoData.js` file to include keys on the `menuItems`.
