### ISSUE TITLE
Add support for nested grid reducers

### ISSUE THREAD

**Issue by drownbes** [bencripps/react-redux-grid#95]
This code would not work with current implementation of stateGetter.js
```javascript
import { Reducers as gridReducers } from 'react-redux-grid'
export default combineReducers({
  routing: routerReducer,
  grid: combineReducers(gridReducers),
  account,
  settings,
  segments
})
```
ReducerKeys options could be string or an array. In example above `reducerKeys='grid'`.

**Comment by bencripps** [comment]
Hmm, that's not currently part of the API design, but I could see the value, so thanks for posting!

This is currently how the import of grid reducers is designed -- does this not work for your implementation?

```js
import { Reducers as gridReducers } from 'react-redux-grid'

export default combineReducers({
  routing: routerReducer,
  account,
  settings,
  segments,
  ...gridReducers,
})
```

**Comment by drownbes** [comment]
@bencripps Yes. It is working for me but I don't like how my store is looking with spread gridReducers. So that do you think about put more power in `reducerKeys` property?

**Comment by bencripps** [comment]
Ah ok. Yeah I could see the value in only having a single reducer for grid -- but that poses a couple issues:

1. it makes grabbing state from grid, for a particular item (data, columns, pagination) a little more cumbersome.
2. It's a breaking change, which would require developers to change their configurations.
3. Apart from making the store a little cleaner, there's no added benefit.

I'd like to see the implementation where it works both ways (so it's not a breaking change), but I think this is low on the totem poll for features to implement. If you'd like to take a crack at implementing that would be awesome! Otherwise I will mark it as help wanted, and get to it as soon as I can.
